#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
      tier: frontend
      version: 1.0.0
#pod tempalte
  template:
    metadata:
      labels:
        app: node-app
        tier: frontend
        version: 1.0.0
    spec: # Pod spec
      containers:
      - name: node-container
        image: #deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-app
      tier: frontend
      version: 1.0.0
#pod tempalte
  template:
    metadata:
      labels:
        app: node-app
        tier: frontend
        version: 1.0.0
    spec: # Pod spec
      containers:
      - name: node-container
        image: laly9999/node-express-app:4
        ports:
        - containerPort: 3000
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: node-app
        ports:
        - containerPort: 3000
        
        
